# Generated by Django 5.2.4 on 2025-07-12 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'annonce")),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('currency', models.CharField(default='XOF', max_length=10, verbose_name='Devise')),
                ('property_type', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('villa', 'Villa'), ('terrain', 'Terrain'), ('bureau', 'Bureau'), ('commercial', 'Local Commercial'), ('autre', 'Autre')], max_length=50, verbose_name='Type de propriété')),
                ('status', models.CharField(choices=[('a_vendre', 'À Vendre'), ('a_louer', 'À Louer'), ('vendu', 'Vendu'), ('loue', 'Loué')], default='a_vendre', max_length=20, verbose_name='Statut')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier/Arrondissement')),
                ('country', models.CharField(default='Bénin', max_length=100, verbose_name='Pays')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('bedrooms', models.IntegerField(blank=True, null=True, verbose_name='Nombre de chambres')),
                ('bathrooms', models.IntegerField(blank=True, null=True, verbose_name='Nombre de salles de bain')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superficie (m²)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Agent immobilier')),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', verbose_name='Image')),
                ('is_main', models.BooleanField(default=False, verbose_name='Image principale')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Image de Propriété',
                'verbose_name_plural': 'Images de Propriété',
            },
        ),
    ]
