# Generated by Django 5.2.4 on 2025-07-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='boosted_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Boosté jusqu'au"),
        ),
        migrations.AddField(
            model_name='property',
            name='is_furnished',
            field=models.BooleanField(default=False, verbose_name='Meublé'),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('Vente', 'Vente'), ('Location', 'Location')], default='Vente', max_length=10, verbose_name="Type d'annonce"),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Maison', 'Maison'), ('Appartement', 'Appartement'), ('Terrain', 'Terrain')], max_length=50, verbose_name='Type de propriété'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='Statut de validation'),
        ),
    ]
