# Generated by Django 5.2.4 on 2025-07-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(default='fr', max_length=10, verbose_name='Langue'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pseudo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pseudo'),
        ),
    ]
