# Generated by Django 5.2.4 on 2025-07-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_air_conditioning',
            field=models.BooleanField(default=False, verbose_name='Dispose de la climatisation'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_balcony',
            field=models.BooleanField(default=False, verbose_name="Dispose d'un balcon"),
        ),
        migrations.AddField(
            model_name='property',
            name='has_garden',
            field=models.BooleanField(default=False, verbose_name="Dispose d'un jardin"),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name="Dispose d'un parking"),
        ),
        migrations.AddField(
            model_name='property',
            name='has_pool',
            field=models.BooleanField(default=False, verbose_name="Dispose d'une piscine"),
        ),
    ]
