# Generated by Django 5.2.4 on 2025-07-14 19:14

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_has_air_conditioning_property_has_balcony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=properties.models.property_image_upload_path, verbose_name='Image'),
        ),
    ]
